---
- name: installs & run nginx
  hosts: all
  remote_user: ubuntu
  become: yes

  pre_tasks:
    - name: installs python before nginx
      apt:
        name: python
        state: latest
  roles:
  - nginx
