---
- name: installs & run nginx
  hosts: webservers
  remote_user: ubuntu
  become: yes

  pre_tasks:
    - name: installs python before nginx
      apt:
        update_cache: yes
        name: python
        state: latest
    - name: install pip 
      apt:
        name: python3-pip
        state: latest
  roles:
  - nginx
  - docker
